[package]
name = "transforms"
version = "0.1.8"
edition = "2021"
description = "A transform library to track reference frames and provide transforms between them."
license = "MIT"
repository = "https://github.com/dHofmeister/transforms"

[features]
tf2-bridge = ["dep:r2r"] 

[dependencies]
log = "0.4.22"
thiserror = "1.0.64"
approx = "0.5.1"
r2r = { version = "0.9.3", optional = true }

[dev-dependencies]
env_logger = "0.11.5"
