[package]
name = "transforms"
version = "0.1.9"
edition = "2021"
description = "A transform library to track reference frames and provide transforms between them."
license = "MIT"
repository = "https://github.com/dHofmeister/transforms"

[dependencies]
log = "0.4.22"
thiserror = "1.0.64"
approx = "0.5.1"

[dev-dependencies]
env_logger = "0.11.5"
