name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests async
      run: cargo test --verbose --features async -- async
    - name: Run example sync_minimal
      run: cargo run --example sync_minimal
    - name: Run example sync_polling
      run: cargo run --example sync_polling
    - name: Run example async_await
      run: cargo run --example async_await --features async

